services:
  crivo-init:
    image: python:bookworm
    user: root
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - ./crivo/init.sh:/app/entrypoint.sh
      - ./crivo/process-metadata.py:/app/process-metadata.py
      - defectdojo_crivo:/app/crivo-metadata:rw
    restart: "no"
