services:
  crivo-init:
    image: curlimages/curl
    user: root
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - ./crivo/init.sh:/app/entrypoint.sh
      - defectdojo_crivo:/app/crivo-metadata:rw
    restart: "no"
