# Generated by Django 5.1.7 on 2025-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_plugin", "0002_vote_is_model_inference_alter_vote_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("finding_id", models.IntegerField()),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("risk_class", models.CharField(choices=[("NA", "NA"), ("Mild", "Mild"), ("Moderate", "Moderate"), ("Severe", "Severe"), ("Critical", "Critical")], max_length=10)),
                ("risk_num", models.CharField(choices=[("NV", "NV"), ("0", "0"), ("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6"), ("7", "7"), ("8", "8"), ("9", "9"), ("10", "10")], max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_model_inference", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "risks",
            },
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
        migrations.AddIndex(
            model_name="risk",
            index=models.Index(fields=["finding_id", "user_id"], name="risks_finding_c3ec1d_idx"),
        ),
    ]
