# Generated by Django 5.1.7 on 2025-04-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("finding_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("result_id", models.CharField(max_length=50)),
                (
                    "vote_class",
                    models.CharField(
                        choices=[
                            ("NA", "NA"),
                            ("Mild", "Mild"),
                            ("Moderate", "Moderate"),
                            ("Severe", "Severe"),
                            ("Critical", "Critical"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "vote_num",
                    models.CharField(
                        choices=[
                            ("NV", "NV"),
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "votes",
                "indexes": [models.Index(fields=["finding_id", "user_id"], name="votes_finding_d1bd89_idx")],
            },
        ),
    ]
